### ISSUE TITLE
Proper casing for Bech32m

### ISSUE THREAD

**Issue by sbddesign** [sbddesign/bech32m-adoption#18]
Should it be:
1. bech32m (persistently lowercased)
2. Bech32m (persistently uppercased)
3. Bech32m / `bech32m` (uppercased, except when referencing as code)
4. Bech32m / bech32m / `bech32m` (contextual -- uppercased when part of a title, lowercased when in the middle of a sentence, and lowercased when referenced in code)

I'd argue it's 3 -- treat it like a proper noun and uppercase it, except when referencing in code. Taking this styling from [BIP-350](https://github.com/bitcoin/bips/blob/master/bip-0350.mediawiki).

**Comment by Xekyo** [comment]
This clearly settles it :zany_face::
![image](https://user-images.githubusercontent.com/4060799/190706083-6bac7a27-6323-4177-b6c5-931cbf50b16b.png)

Srsly tho, in code everything is written as the code is cased (which in python usually is snake_case), and I think otherwise "Bech32m" should be correct.

**Comment by sbddesign** [comment]
Cool, going with option 3 then.
