### ISSUE TITLE
Improve Search Rankings

### ISSUE THREAD

**Issue by DanGould** [sbddesign/bech32m-adoption#35]
When I type "when taproot" into google this page does not show up in the first handful of results. These issues come up when I run an [SEO Check](https://freetools.seobility.net/en/seocheck/whentaproot.org) which gives the site a score of 70/100.

- [ ] [Use 301 redirects to drive traffic to URLS with the same domain and sub domain (www and non-www subdomain).](https://freetools.seobility.net/en/seocheck/whentaproot.org#redirect)
Very important!

  [Redirect report](https://freetools.seobility.net/en/redirectcheck/check?url=whentaproot.org&expected=https)
> ❗️ no https://www.whentaproot.org or http://www.whentaproot.org
redirect. Add an A record 

### Apache redirect config: 

```
RewriteEngine On
RewriteCond %{HTTP_HOST} !^whentaproot.org$
RewriteRule ^(.*)$ https://whentaproot.org/$1 [R=301,L]
```

### NGINX redirect config

```
server {
    server_name www.whentaproot.org;
    return 301 https://whentaproot.org$request_uri;
}

server {
    server_name whentaproot.org;
    # Server Code
}
```

I think you could also create an A record with your domain provider to point to the same web server

@sbddesign This one is the most critical to have the site ranked and I don't think I can change it.

- [ ] [Try to reduce the number of used JavaScript files.](https://freetools.seobility.net/en/seocheck/whentaproot.org#performance)
Very important!
- [ ] [Improve the text of the meta description.](https://freetools.seobility.net/en/seocheck/whentaproot.org#meta-description)  #36
Important!
- [ ] [The page title should be better suited to the content of the page.](https://freetools.seobility.net/en/seocheck/whentaproot.org#page-content)
Important!
- [ ] [Use good alternative descriptions (alt attributes) for your images.](https://freetools.seobility.net/en/seocheck/whentaproot.org#images)
Important!

**Comment by sbddesign** [comment]
Thanks for raising this issue @DanGould. There's a lot contained in here and I have different feelings about each one.

## Notes on purpose of SEO

It's worth discussing first what is the purpose of SEO. It's one of those words that can have a lot of different meanings. Within the context of WhenTaproot, what is the goal of SEO? Who are we trying to reach?

Is this to attract people who are not familiar with the project, but are searching for relevant or related topics? If so, we really want to optimize for related terms. "does [x wallet] support taproot", "what does taproot do", etc.

Or is this merely for convenience, so that people who have already heard of this project can find it quickly?
If so, we might want to be optimizing for stuff like "when taproot", "current taproot adoption", etc.

## General notes on seobility

I don't put much stock in sites like "seobility" and their free scan tools. In my experience, SEO is a very broad topic and "good SEO" is going to depend on which people you are trying to reach and which sorts of search terms you can actually compete on (which is a game of economics).

IMO, these free scan tools are tools for their marketing funnel and should not be taken as gospel-truth SEO advice.

## Specific comments on your checkboxes

### Add a `www` with a redirect

Sure, we can do that. Don't think it will improve SEO but might as well have it for people who are hardwired to still type `www` (valid concern). Addressing in #38.

### Improve text meta description

I like this. I don't think this is going to rocket boost us to the top, but I really like the UX of having a snappier and tidier description. Approved and pending one other text review on #36.

### Page title

"The page title should be better suited to the content of the page". This is an example of free scan tools not understanding context. `When Taproot? | Bitcoin Bech32m Adoption Tracking` is extremely well suited to the content of the page!

So next question to ask: who do we want this site to appear in search results for, and what do we think they will be searching for? If we can come to a common agreement around that, then we can start optimizing titles of pages for specific search terms. But without determining that, there is no use monkeying with it.

## Use good descriptions on images

As far as I can tell, all our images have alt tags. They all describe what's in the image, as is correct for `a11y` reasons. Some alt tags are left blank because they provide nothing of value to a user with a screenreader (UI garnishes and not actual content). The blank alt tag is kind of an `a11y` standard.

If we wanted to, we could pack some of these alt tags with all sorts of juicy bait for search engine crawlers. But again, that first requires us to determine who we are trying to reach, which terms they are searching for, and which terms we can compete on in an economical manner.

## Final notes

In my opinion, trying to compete on search terms is not a good use of time for this project. I think WhenTaproot is sort of temporary project, and better to push more on social media and in developer and product manager circles. However, I'd be curious to hear others opinions on this matter.

So I think we move forward with #36 and #38, and we can discuss the other two a little further and see if there are reasonable goals we can achieve there.

**Comment by sbddesign** [comment]
Also, I forgot to comment on limit use of javascript files. This would be a big fix and require a bunch of re-architecting. This is one of those things that lacks context. NextJS basically loads stuff dynamically into the page. The first load is very quick, and it uses low-res images, then dynamically injects more stuff into the page. So sure, there's a bit of JS there, but this isn't like "the entire website is waiting for one 10MB javascript file to load".

**Comment by larisoft** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.shanefontaine, @r4ds3c, @Aruk, @Estelle36, @MatejLach, @Gitleyla, @MattConflitti, @SoroushBr, @PresidentNick, @suryagh, @JimiHFord, @ramy-sharif, @Pricelezz1, @musdom, @nikita, @lopezdp, @D4n13l3k00, @ZoneMix, @0xHexE, @therealparmesh
